### ISSUE TITLE
Which library does it need to be able to load ofa.utils?

### ISSUE THREAD

**Issue by ad1r20** [simonesarti/AEP#1]

**Comment by simonesarti** [comment]
the package is called "ofa"

**Comment by ad1r20** [comment]
and where can I find it, or should the ofa network be installed ?

**Comment by ad1r20** [comment]
and it can be found here: https://pypi.org/project/ofa/. Thanks you !!!!

**Comment by simonesarti** [comment]
yes, that one :)
